// Writes a crawler-readable copy of the Outreach catalogue and project list
// into outreach.html, generated from the same COURSES / PROJECTS data the
// page uses at runtime.
//
// Why: the course cards, course details and project list are rendered by
// JavaScript, so search engines and AI crawlers that read the raw HTML only
// see template placeholders such as {{ c.titleA }}. This script adds:
//   1. a static HTML version of the content, wrapped in <sc-if value="{{ false }}">
//      so the page runtime never displays it (visitors see no change), while
//      crawlers reading the HTML file get the full text;
//   2. Schema.org JSON-LD (ItemList of Course) in <head>.
//
// Usage: node scripts/prerender.mjs
// Run it after editing COURSES or PROJECTS in outreach.html. It also runs on
// every Netlify deploy (see netlify.toml). It is idempotent and never fails
// the build: if something is off it prints a warning and leaves files as-is.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://ilariafiore.com';
const PERSON_ID = `${SITE}/#person`;

const esc = (s) => String(s ?? '')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;')
  // never emit template syntax inside the template
  .replace(/\{\{/g, '{&#8203;{');
const br = (s) => esc(s).replace(/\n/g, ' ');

function grabArray(src, name) {
  const start = src.indexOf(`const ${name} = [`);
  if (start < 0) throw new Error(`const ${name} not found`);
  const open = src.indexOf('[', start);
  let depth = 0, i = open, quote = null;
  for (; i < src.length; i++) {
    const c = src[i];
    if (quote) {
      if (c === '\\') { i++; continue; }
      if (c === quote) quote = null;
      continue;
    }
    if (c === "'" || c === '"' || c === '`') { quote = c; continue; }
    if (c === '[') depth++;
    else if (c === ']' && --depth === 0) break;
  }
  // The data lives in the site's own page script; evaluate it as a literal.
  return new Function(`return ${src.slice(open, i + 1)};`)();
}

function replaceBetween(src, tag, content, insertBefore) {
  const a = `<!-- ${tag}:START (generated by scripts/prerender.mjs, do not edit by hand) -->`;
  const b = `<!-- ${tag}:END -->`;
  const block = `${a}\n${content}\n${b}`;
  const i = src.indexOf(a.slice(0, a.indexOf(' (')));
  const j = src.indexOf(b);
  if (i >= 0 && j > i) return src.slice(0, i) + block + src.slice(j + b.length);
  const k = src.indexOf(insertBefore);
  if (k < 0) throw new Error(`anchor for ${tag} not found`);
  const lineStart = src.lastIndexOf('\n', k) + 1;
  return src.slice(0, lineStart) + block + '\n' + src.slice(lineStart);
}

function coursesHtml(courses) {
  const items = courses.map((c, i) => {
    const specs = c.specs.map((s) => `<dt>${esc(s.k)}</dt><dd>${esc(s.v)}${s.sym ? esc(s.sym) : ''}</dd>`).join('');
    const sdgs = (c.sdgs || []).map((g) => `SDG ${esc(g.n)} ${esc(g.name)}`).join(', ');
    return [
      `<article>`,
      `<h3>Course ${String(i + 1).padStart(2, '0')}: ${esc(c.title)}</h3>`,
      `<p>${(c.tags || []).map(esc).join(' · ')}</p>`,
      `<p>${esc(c.summary)}</p>`,
      `<h4>${esc(c.learnLabel)}</h4>`,
      `<ul>${(c.learn || []).map((l) => `<li>${esc(l)}</li>`).join('')}</ul>`,
      `<dl>${specs}</dl>`,
      c.material ? `<p>Material included: ${esc(c.material)}</p>` : '',
      sdgs ? `<p>Sustainable Development Goals: ${sdgs}</p>` : '',
      `</article>`,
    ].filter(Boolean).join('\n');
  });
  return `<sc-if value="{{ false }}">\n<div data-static-fallback="courses">\n<h2>Space and STEM courses and workshops</h2>\n${items.join('\n')}\n</div>\n</sc-if>`;
}

function projectsHtml(projects) {
  const items = projects.map((p) => {
    const title = p.nameEn ? `${br(p.name)} (${esc(p.nameEn)})` : br(p.name);
    const specs = (p.specs || []).map((s) => `<dt>${esc(s.k)}</dt><dd>${br(s.v)}</dd>`).join('');
    return [
      `<article>`,
      `<h3>${title}</h3>`,
      `<p>${br(p.host)} · ${esc(p.year)}</p>`,
      `<p>${esc(p.desc)}</p>`,
      specs ? `<dl>${specs}</dl>` : '',
      p.href ? `<p><a href="${esc(p.href)}">${esc(p.linkLabel || 'More')}</a></p>` : '',
      `</article>`,
    ].filter(Boolean).join('\n');
  });
  return `<sc-if value="{{ false }}">\n<div data-static-fallback="projects">\n<h2>Outreach, workshops &amp; events</h2>\n${items.join('\n')}\n</div>\n</sc-if>`;
}

function coursesJsonLd(courses) {
  const data = {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: 'Space and STEM courses and workshops by Ilaria Fiore',
    url: `${SITE}/outreach#courses`,
    itemListElement: courses.map((c, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      item: {
        '@type': 'Course',
        name: c.title,
        description: c.summary,
        teaches: c.learn,
        keywords: (c.tags || []).join(', '),
        provider: { '@type': 'Person', '@id': PERSON_ID, name: 'Ilaria Fiore', url: `${SITE}/` },
        ...(c.specs.find((s) => /age|target/i.test(s.k))
          ? { audience: { '@type': 'Audience', audienceType: c.specs.find((s) => /age|target/i.test(s.k)).v + (c.specs.find((s) => /age|target/i.test(s.k)).sym || '') } }
          : {}),
      },
    })),
  };
  return `<script type="application/ld+json">\n${JSON.stringify(data, null, 2).replace(/<\//g, '<\\/')}\n</script>`;
}

function run() {
  const file = join(ROOT, 'outreach.html');
  let src = readFileSync(file, 'utf8');
  const courses = grabArray(src, 'COURSES');
  const projects = grabArray(src, 'PROJECTS');

  src = replaceBetween(src, 'STATIC-COURSES', coursesHtml(courses),
    '<div style="position:relative;width:min(1760px,100%);margin:0 auto;padding-left:');
  src = replaceBetween(src, 'STATIC-PROJECTS', projectsHtml(projects),
    '<sc-for list="{{ projects }}"');
  src = replaceBetween(src, 'JSONLD-COURSES', coursesJsonLd(courses), '</head>');

  writeFileSync(file, src);
  console.log(`prerender: outreach.html updated (${courses.length} courses, ${projects.length} projects)`);
}

try {
  run();
} catch (err) {
  console.warn(`prerender: skipped, ${err.message}`);
}
